version: 1.0.{build}
branches:
  only:
  - master
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: ef/+bgM0vciXfUTX63A13/KUdWX4KndGaQMcXn4RahqZdQuRlRPyvDb1Irw7+d+C
  on:
    branch: master